---
# tasks file for mapr-pig

- name: install mapr-pig
  yum: name=mapr-pig-{{pig_version}}.{{pig_build}} state=present
  when: ansible_distribution in ('CentOS', 'RedHat', 'Amazon')
  environment: proxy_env
